version: 0.2
env:
  git-credential-helper: yes
  variables:
    REPOSITORY: $REPOSITORY # CodeBuild-defined environment variable
phases:
  build:
    commands:
      - git clone https://git-codecommit.$AWS_REGION.amazonaws.com/v1/repos/$REPOSITORY
      - cd aws_tester
      - TAG=$CODEBUILD_BUILD_NUMBERx
      - COMMIT_ID=$CODEBUILD_RESOLVED_SOURCE_VERSION
      - git tag $TAG $COMMIT_ID
      - git push origin $TAG
artifacts:
  files:
    - '*'
    - '**/*'
